// <auto-generated />
using System;
using BookingCare.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260328122403_seed_new_data")]
    partial class seed_new_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BookerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.AppointmentService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceOverride")
                        .HasColumnType("float");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitizenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("SubSpecialties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkingHistory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-minh.jpg",
                            CitizenId = "001075123456",
                            DateOfBirth = new DateTime(1975, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên gia tiêu hóa.",
                            DoctorCode = "BS-001",
                            ExperienceYears = 25,
                            FullName = "PGS.TS Nguyễn Trọng Minh",
                            Gender = 0,
                            Position = 3,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SubSpecialties = "[\"Ti\\u00EAu h\\u00F3a\",\"N\\u1ED9i soi\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV Bạch Mai"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-van.jpg",
                            CitizenId = "001182654321",
                            DateOfBirth = new DateTime(1982, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên gia xương khớp.",
                            DoctorCode = "BS-002",
                            ExperienceYears = 15,
                            FullName = "ThS.BS Đỗ Thị Tường Vân",
                            Gender = 1,
                            Position = 1,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111101"),
                            SubSpecialties = "[\"X\\u01B0\\u01A1ng kh\\u1EDBp\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV Chợ Rẫy"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-nam.jpg",
                            CitizenId = "001078987654",
                            DateOfBirth = new DateTime(1978, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên gia tim mạch.",
                            DoctorCode = "BS-003",
                            ExperienceYears = 20,
                            FullName = "BSCKII Phạm Thành Nam",
                            Gender = 0,
                            Position = 2,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111103"),
                            SubSpecialties = "[\"Tim m\\u1EA1ch\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "Viện Tim TP.HCM"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-ha.jpg",
                            CitizenId = "001185456789",
                            DateOfBirth = new DateTime(1985, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên khoa sản.",
                            DoctorCode = "BS-004",
                            ExperienceYears = 12,
                            FullName = "ThS.BS Lê Thị Thu Hà",
                            Gender = 1,
                            Position = 1,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111104"),
                            SubSpecialties = "[\"S\\u1EA3n khoa\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV Từ Dũ"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-duc.jpg",
                            CitizenId = "001088112233",
                            DateOfBirth = new DateTime(1988, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bác sĩ nhi khoa.",
                            DoctorCode = "BS-005",
                            ExperienceYears = 10,
                            FullName = "BSCKI Hoàng Văn Đức",
                            Gender = 0,
                            Position = 1,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111105"),
                            SubSpecialties = "[\"Nhi khoa\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV Nhi TW"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-huong.jpg",
                            CitizenId = "001190334455",
                            DateOfBirth = new DateTime(1990, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bác sĩ da liễu.",
                            DoctorCode = "BS-006",
                            ExperienceYears = 8,
                            FullName = "BS Trần Mai Hương",
                            Gender = 1,
                            Position = 0,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111106"),
                            SubSpecialties = "[\"Da li\\u1EC5u\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "Phòng khám Da liễu HN"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-tuan.jpg",
                            CitizenId = "001072998877",
                            DateOfBirth = new DateTime(1972, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bác sĩ TMH.",
                            DoctorCode = "BS-007",
                            ExperienceYears = 28,
                            FullName = "BSCKII Vũ Anh Tuấn",
                            Gender = 0,
                            Position = 2,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111107"),
                            SubSpecialties = "[\"Tai M\\u0169i H\\u1ECDng\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV Tai Mũi Họng TW"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333308"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-nhung.jpg",
                            CitizenId = "001183223344",
                            DateOfBirth = new DateTime(1983, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bác sĩ mắt.",
                            DoctorCode = "BS-008",
                            ExperienceYears = 14,
                            FullName = "ThS.BS Bùi Tuyết Nhung",
                            Gender = 1,
                            Position = 1,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111108"),
                            SubSpecialties = "[\"Nh\\u00E3n khoa\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV Mắt TW"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333309"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-viet.jpg",
                            CitizenId = "001065776655",
                            DateOfBirth = new DateTime(1965, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bác sĩ thần kinh.",
                            DoctorCode = "BS-009",
                            ExperienceYears = 35,
                            FullName = "PGS.TS Ngô Quốc Việt",
                            Gender = 0,
                            Position = 3,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111109"),
                            SubSpecialties = "[\"Th\\u1EA7n kinh\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "ĐH Y Hà Nội"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333310"),
                            AvatarUrl = "https://storage.googleapis.com/bookingcare/doctors/bs-dung.jpg",
                            CitizenId = "001087009988",
                            DateOfBirth = new DateTime(1987, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nha sĩ.",
                            DoctorCode = "BS-010",
                            ExperienceYears = 11,
                            FullName = "BSCKI Đặng Tiến Dũng",
                            Gender = 0,
                            Position = 1,
                            SpecialtyId = new Guid("11111111-1111-1111-1111-111111111110"),
                            SubSpecialties = "[\"R\\u0103ng H\\u00E0m M\\u1EB7t\"]",
                            UserId = new Guid("021ac6a0-18c5-4e1e-6386-08de8652903f"),
                            WorkingHistory = "BV RHM TW"
                        });
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActioned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ShareProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Content")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemplateMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("CitizenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.ProfileShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SharePermission")
                        .HasColumnType("int");

                    b.Property<int>("ShareStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SharedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProfileShares");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Receptionist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitizenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ReceptionistCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám xương khớp tổng quát.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333302"),
                            DurationInMinutes = 15,
                            IsActive = true,
                            Name = "Khám chuyên khoa Cơ xương khớp",
                            Price = 300000.0,
                            ServiceCode = "SRV-001",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội soi không đau.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333301"),
                            DurationInMinutes = 45,
                            IsActive = true,
                            Name = "Nội soi dạ dày gây mê",
                            Price = 1200000.0,
                            ServiceCode = "SRV-002",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Siêu âm chức năng tim.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333303"),
                            DurationInMinutes = 20,
                            IsActive = true,
                            Name = "Siêu âm tim Dopler màu",
                            Price = 450000.0,
                            ServiceCode = "SRV-003",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Siêu âm tầm soát thai nhi.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333304"),
                            DurationInMinutes = 30,
                            IsActive = true,
                            Name = "Siêu âm thai 4D",
                            Price = 500000.0,
                            ServiceCode = "SRV-004",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám sức khỏe cho trẻ.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333305"),
                            DurationInMinutes = 15,
                            IsActive = true,
                            Name = "Khám Nhi tổng quát",
                            Price = 200000.0,
                            ServiceCode = "SRV-005",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xử lý mụn công nghệ cao.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333306"),
                            DurationInMinutes = 40,
                            IsActive = true,
                            Name = "Điều trị mụn Laser",
                            Price = 800000.0,
                            ServiceCode = "SRV-006",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội soi họng và tai.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333307"),
                            DurationInMinutes = 15,
                            IsActive = true,
                            Name = "Nội soi Tai Mũi Họng",
                            Price = 250000.0,
                            ServiceCode = "SRV-007",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiểm tra độ cận/viễn.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333308"),
                            DurationInMinutes = 20,
                            IsActive = true,
                            Name = "Đo khúc xạ mắt",
                            Price = 150000.0,
                            ServiceCode = "SRV-008",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám chức năng não.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333309"),
                            DurationInMinutes = 45,
                            IsActive = true,
                            Name = "Đo điện não đồ EEG",
                            Price = 600000.0,
                            ServiceCode = "SRV-009",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222210"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tiểu phẫu răng miệng.",
                            DoctorId = new Guid("33333333-3333-3333-3333-333333333310"),
                            DurationInMinutes = 60,
                            IsActive = true,
                            Name = "Nhổ răng khôn mọc lệch",
                            Price = 1500000.0,
                            ServiceCode = "SRV-010",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám và điều trị các bệnh lý về hệ vận động, xương khớp.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/co-xuong-khop.jpg",
                            Name = "Cơ Xương Khớp",
                            SpecialtyCode = "CK-001",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên khoa dạ dày, đại tràng, gan mật và nội soi tiêu hóa.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/tieu-hoa.jpg",
                            Name = "Tiêu hóa",
                            SpecialtyCode = "CK-002",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Điều trị cao huyết áp, suy tim và các bệnh lý mạch vành.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/tim-mach.jpg",
                            Name = "Tim mạch",
                            SpecialtyCode = "CK-003",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chăm sóc thai kỳ, sinh sản và các bệnh lý phụ khoa nữ giới.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/san-phu-khoa.jpg",
                            Name = "Sản Phụ khoa",
                            SpecialtyCode = "CK-004",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám và điều trị các bệnh lý thường gặp ở trẻ sơ sinh và trẻ nhỏ.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/nhi-khoa.jpg",
                            Name = "Nhi khoa",
                            SpecialtyCode = "CK-005",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Điều trị mụn, nám, dị ứng da và thẩm mỹ công nghệ cao.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/da-lieu.jpg",
                            Name = "Da liễu",
                            SpecialtyCode = "CK-006",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám và điều trị viêm xoang, viêm họng, các bệnh lý tai mũi họng.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/tai-mui-hong.jpg",
                            Name = "Tai Mũi Họng",
                            SpecialtyCode = "CK-007",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám mắt tổng quát, đo thị lực và điều trị tật khúc xạ.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/mat.jpg",
                            Name = "Mắt",
                            SpecialtyCode = "CK-008",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chẩn đoán rối loạn thần kinh, đau đầu, tiền đình và não bộ.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/than-kinh.jpg",
                            Name = "Thần kinh",
                            SpecialtyCode = "CK-009",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            CreatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nha khoa tổng quát, nhổ răng khôn và thẩm mỹ răng sứ.",
                            ImageUrl = "https://storage.googleapis.com/bookingcare/specialties/rang-ham-mat.jpg",
                            Name = "Răng Hàm Mặt",
                            SpecialtyCode = "CK-010",
                            UpdatedDate = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.WorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextAvailableAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.WorkSessionService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("WorkSessionServices");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.PatientProfile", "PatientProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingCare.Domain.Entities.WorkSession", "WorkSession")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.AppointmentService", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingCare.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Service", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Services")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.WorkSession", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.Doctor", "Doctor")
                        .WithMany("WorkSessions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.WorkSessionService", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.Service", "Service")
                        .WithMany("WorkSessionServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingCare.Domain.Entities.WorkSession", "WorkSession")
                        .WithMany("WorkSessionServices")
                        .HasForeignKey("WorkSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingCare.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BookingCare.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.PatientProfile", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Service", b =>
                {
                    b.Navigation("WorkSessionServices");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("BookingCare.Domain.Entities.WorkSession", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("WorkSessionServices");
                });
#pragma warning restore 612, 618
        }
    }
}
